---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: homelab-coreos-minipc
description: Frontend application node for NAB9 mini PC

base-image: ghcr.io/ublue-os/ucore
image-version: latest

modules:
  # Enable RPM Fusion repos for intel-media-driver and ffmpeg
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    install:
      # Intel VAAPI hardware acceleration packages
      - intel-media-driver      # iHD driver for Intel Gen 8+ (Broadwell and newer)
      - libva                   # VAAPI core library
      - libva-utils             # vainfo and debugging tools
      - ffmpeg                  # Hardware-accelerated encoding/decoding
      - gstreamer1-vaapi        # GStreamer VAAPI plugin

  # Copy system configuration files (includes /etc/profile.d/intel-vaapi.sh)
  - type: files
    files:
      - source: system
        destination: /

  # Enable systemd units for WireGuard and NFS mounts
  - type: systemd
    system:
      enabled:
        - wg-quick@wg0.service
        - mnt-nas-media.mount
        - mnt-nas-nextcloud.mount
        - mnt-nas-immich.mount

  - type: signing
