# Cloud Services - Nextcloud with Collabora
# These services store data on NFS mounts and are accessed via reverse proxy

services:
  nextcloud-db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_DB=nextcloud
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${APPDATA_PATH}/nextcloud/db:/var/lib/postgresql/data:z
    networks:
      - nextcloud
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud"]
      interval: 30s
      timeout: 10s
      retries: 5

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - label=disable
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-100}
      - TZ=${TZ:-America/Chicago}
      - CHECK_DATA_DIRECTORY_PERMISSIONS=false
    volumes:
      - ${APPDATA_PATH}/nextcloud/config:/config
      - /mnt/nas-nextcloud:/data
    ports:
      - "8080:443"
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
      collabora:
        condition: service_started
    networks:
      - nextcloud
    labels:
      - "homepage.group=Cloud"
      - "homepage.name=Nextcloud"
      - "homepage.icon=nextcloud.png"
      - "homepage.href=https://minipc.lan:8080"

  collabora:
    image: collabora/code
    container_name: nextcloud-collabora
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - domain=${NEXTCLOUD_DOMAIN}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - username=admin
      - password=${COLLABORA_PASSWORD}
    ports:
      - "9980:9980"
    networks:
      - nextcloud
    labels:
      - "homepage.group=Cloud"
      - "homepage.name=Collabora"
      - "homepage.icon=collabora.png"
      - "homepage.href=http://minipc.lan:9980"

  harp:
    image: ghcr.io/nextcloud/nextcloud-appapi-harp:release
    container_name: nextcloud-harp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - label=disable
    environment:
      - HP_SHARED_KEY=${HP_SHARED_KEY}
      - NC_INSTANCE_URL=https://${NEXTCLOUD_DOMAIN}
      - HP_EXAPPS_ADDRESS=${HP_EXAPPS_ADDRESS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - harp_certs:/certs
    ports:
      - "8780:8780"
      - "8782:8782"
    networks:
      - nextcloud

networks:
  nextcloud:
    name: nextcloud
    driver: bridge

volumes:
  harp_certs:
