# Media Services - Plex and Jellyfin with Intel QuickSync hardware transcoding
# These services have direct WAN access for streaming to remote users

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
      - VERSION=docker
      # Hardware transcoding
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
      - PLEX_TRANSCODE_TEMP_DIRECTORY=/transcode
    volumes:
      # Plex configuration and metadata
      - ${APPDATA_PATH}/plex/config:/config:Z
      # Plex transcode directory on fast local storage
      - ${APPDATA_PATH}/plex/transcode:/transcode:Z
      # Media library (read-only from NFS)
      - /mnt/nas-media:/media:ro
    tmpfs:
      - /config/Library/Application Support/Plex Media Server/Codecs:size=200m,uid=1001,gid=1001,mode=0755,exec
    devices:
      # Intel QuickSync hardware transcoding
      - /dev/dri:/dev/dri
    labels:
      - "homepage.group=Media"
      - "homepage.name=Plex"
      - "homepage.icon=plex.png"
      - "homepage.href=http://minipc.lan:32400"
      - "homepage.widget.type=plex"
      - "homepage.widget.url=http://minipc.lan:32400"
      - "homepage.widget.key=${PLEX_API_KEY}"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
      # Hardware transcoding
      - LIBVA_DRIVER_NAME=iHD
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLIC_URL}
    volumes:
      # Jellyfin configuration and metadata
      - ${APPDATA_PATH}/jellyfin/config:/config:Z
      - ${APPDATA_PATH}/jellyfin/cache:/cache:Z
      - ${APPDATA_PATH}/jellyfin/scripts:/scripts:Z
      - ${APPDATA_PATH}/jellyfin/transcode:/transcode:Z
      # Media library (read-only from NFS)
      - /mnt/nas-media:/media:ro
    devices:
      # Intel QuickSync hardware transcoding
      - /dev/dri:/dev/dri
    group_add:
      - "105"
    labels:
      - "homepage.group=Media"
      - "homepage.name=Jellyfin"
      - "homepage.icon=jellyfin.png"
      - "homepage.href=http://minipc.lan:8096"
      - "homepage.widget.type=jellyfin"
      - "homepage.widget.url=http://minipc.lan:8096"
      - "homepage.widget.key=${JELLYFIN_API_KEY}"
      - "homepage.widget.enableBlocks=true"
      - "homepage.widget.enableNowPlaying=true"

  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=${KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS:-#recycle,@eaDir}
    ports:
      - "25600:25600"
    volumes:
      # Komga configuration and database
      - ${APPDATA_PATH}/komga:/config:Z
      # Media libraries (read-only from NFS)
      - /mnt/nas-media/ebooks:/books:ro
      - /mnt/nas-media/manga:/manga:ro
    networks:
      - media
    healthcheck:
      disable: true
    labels:
      - "homepage.group=Media"
      - "homepage.name=Komga"
      - "homepage.icon=komga.png"
      - "homepage.href=http://minipc.lan:25600"

# Networks are not needed for host network mode
# But we can define them for future services if needed
networks:
  media:
    name: media
    driver: bridge
